server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins: "*"
            #              - "http://system.jdzapp.com"
            allowed-headers: "*"
            allowed-methods: "*"
            #              - OPTIONS
            #              - GET
            #              - POST
            max-age: 360000
            # 允许response的head信息
            # 默认仅允许如下6个：
            #   Cache-Control
            #   Content-Language
            #   Content-Type
            #   Expires
            #   Last-Modified
            #   Pragma
            #exposed-headers:

