server:
  port: 8082
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/